num_rounds: 1
num_clients: 1
batch_size: 20
num_classes: 2
num_clients_per_round_fit: 1
num_clients_per_round_eval: 1
config_fit:
  lr: 0.001
  momentum: 0.9
  local_epochs: 10


# num_rounds: 1
# num_clients: 4
# batch_size: 20
# num_classes: 2
# num_clients_per_round_fit: 4
# num_clients_per_round_eval: 4
# config_fit:
#   lr: 0.0001
#   momentum: 0.9
#   local_epochs: 10


# 97

# num_rounds: 1
# num_clients: 1
# batch_size: 20
# num_classes: 2
# num_clients_per_round_fit: 1
# num_clients_per_round_eval: 1
# config_fit:
#   lr: 0.001
#   momentum: 0.9
#   local_epochs: 10

